class CodesV2Generator {
  generate() {
    const codes = [];
    let id = 0;

    const codeGroups = [
      {
        body: 'SBC', name: 'Saudi Building Code', country: 'Saudi Arabia',
        standards: [
          { code: 'SBC 201', title: 'Structural - Loads & Forces', year: 2018 },
          { code: 'SBC 301', title: 'Structural - Concrete Structures', year: 2018 },
          { code: 'SBC 302', title: 'Structural - Steel Structures', year: 2018 },
          { code: 'SBC 303', title: 'Structural - Masonry Structures', year: 2018 },
          { code: 'SBC 304', title: 'Architectural - Finishes & Cladding', year: 2018 },
          { code: 'SBC 401', title: 'Mechanical - Plumbing & HVAC', year: 2018 },
          { code: 'SBC 402', title: 'Electrical - Power & Lighting', year: 2018 },
          { code: 'SBC 403', title: 'Electrical - Low Current Systems', year: 2018 },
          { code: 'SBC 404', title: 'Electrical - Fire Alarm', year: 2018 },
          { code: 'SBC 501', title: 'Fire Protection - General', year: 2018 },
          { code: 'SBC 502', title: 'Fire Protection - Active Systems', year: 2018 },
          { code: 'SBC 601', title: 'Energy Conservation', year: 2018 },
          { code: 'SBC 602', title: 'Mechanical - HVAC Energy', year: 2018 },
          { code: 'SBC 701', title: 'Accessibility', year: 2018 },
          { code: 'SBC 801', title: 'Fire & Life Safety', year: 2018 },
          { code: 'SBC 901', title: 'Existing Buildings', year: 2018 },
        ]
      },
      {
        body: 'IBC', name: 'International Building Code', country: 'USA',
        standards: [
          { code: 'IBC 2018', title: 'International Building Code', year: 2018 },
          { code: 'IBC 2021', title: 'International Building Code', year: 2021 },
          { code: 'IBC 2024', title: 'International Building Code', year: 2024 },
          { code: 'IRC 2018', title: 'International Residential Code', year: 2018 },
          { code: 'IRC 2021', title: 'International Residential Code', year: 2021 },
          { code: 'IECC 2018', title: 'International Energy Conservation Code', year: 2018 },
          { code: 'IECC 2021', title: 'International Energy Conservation Code', year: 2021 },
          { code: 'IFC 2018', title: 'International Fire Code', year: 2018 },
          { code: 'IFC 2021', title: 'International Fire Code', year: 2021 },
          { code: 'IMC 2018', title: 'International Mechanical Code', year: 2018 },
          { code: 'IMC 2021', title: 'International Mechanical Code', year: 2021 },
          { code: 'IPC 2018', title: 'International Plumbing Code', year: 2018 },
          { code: 'IPC 2021', title: 'International Plumbing Code', year: 2021 },
          { code: 'ISPSC 2018', title: 'International Swimming Pool & Spa Code', year: 2018 },
          { code: 'IWUIC 2018', title: 'International Wildland Urban Interface Code', year: 2018 },
        ]
      },
      {
        body: 'ACI', name: 'American Concrete Institute', country: 'USA',
        standards: [
          { code: 'ACI 117', title: 'Specifications for Concrete Tolerances', year: 2018 },
          { code: 'ACI 211', title: 'Proportioning Concrete Mixtures', year: 2022 },
          { code: 'ACI 214', title: 'Evaluation of Concrete Test Results', year: 2021 },
          { code: 'ACI 301', title: 'Specifications for Concrete', year: 2020 },
          { code: 'ACI 302', title: 'Concrete Floor and Slab Construction', year: 2023 },
          { code: 'ACI 304', title: 'Measuring, Mixing, Transporting Concrete', year: 2022 },
          { code: 'ACI 305', title: 'Hot Weather Concreting', year: 2020 },
          { code: 'ACI 306', title: 'Cold Weather Concreting', year: 2021 },
          { code: 'ACI 308', title: 'Curing Concrete', year: 2022 },
          { code: 'ACI 309', title: 'Consolidation of Concrete', year: 2021 },
          { code: 'ACI 311', title: 'Concrete Inspection', year: 2019 },
          { code: 'ACI 318', title: 'Building Code Requirements for Structural Concrete', year: 2019 },
          { code: 'ACI 347', title: 'Formwork for Concrete', year: 2022 },
          { code: 'ACI 350', title: 'Environmental Structures Concrete', year: 2023 },
          { code: 'ACI 351', title: 'Foundations for Dynamic Equipment', year: 2020 },
          { code: 'ACI 352', title: 'Joints in Concrete Structures', year: 2021 },
          { code: 'ACI 355', title: 'Anchors in Concrete', year: 2022 },
          { code: 'ACI 360', title: 'Design of Slabs on Ground', year: 2022 },
          { code: 'ACI 362', title: 'Parking Structures', year: 2021 },
          { code: 'ACI 363', title: 'High Strength Concrete', year: 2022 },
          { code: 'ACI 364', title: 'Concrete Repair Guide', year: 2021 },
          { code: 'ACI 370', title: 'Fiber Reinforced Concrete', year: 2023 },
          { code: 'ACI 374', title: 'Seismic Design of Concrete Structures', year: 2020 },
          { code: 'ACI 440', title: 'FRP Reinforcement', year: 2022 },
          { code: 'ACI 530', title: 'Masonry Structures (with TMS)', year: 2021 },
          { code: 'ACI 543', title: 'Concrete Piles', year: 2022 },
          { code: 'ACI 544', title: 'Fiber Reinforced Concrete', year: 2021 },
          { code: 'ACI 546', title: 'Concrete Repair', year: 2020 },
          { code: 'ACI 562', title: 'Existing Concrete Buildings', year: 2021 },
          { code: 'ACI 601', title: 'Concrete Parking Lots', year: 2022 },
        ]
      },
      {
        body: 'AISC', name: 'American Institute of Steel Construction', country: 'USA',
        standards: [
          { code: 'AISC 360', title: 'Specification for Structural Steel Buildings', year: 2022 },
          { code: 'AISC 341', title: 'Seismic Provisions for Steel Buildings', year: 2021 },
          { code: 'AISC 358', title: 'Prequalified Connections for Seismic Systems', year: 2022 },
          { code: 'AISC 303', title: 'Code of Standard Practice', year: 2021 },
          { code: 'AISC 325', title: 'Steel Construction Manual', year: 2023 },
          { code: 'AISC 327', title: 'Seismic Design Manual', year: 2021 },
          { code: 'AISC 348', title: 'Specification for Hollow Structural Sections', year: 2022 },
          { code: 'AISC 349', title: 'Composite Steel Concrete Structures', year: 2023 },
          { code: 'AISC 370', title: 'Specification for Stainless Steel Buildings', year: 2021 },
          { code: 'AISC 391', title: 'Fire Protection of Steel Structures', year: 2022 },
        ]
      },
      {
        body: 'ASTM', name: 'ASTM International', country: 'USA',
        standards: [
          { code: 'ASTM A36', title: 'Carbon Structural Steel', year: 2020 },
          { code: 'ASTM A53', title: 'Pipe, Steel, Black and Hot-Dipped', year: 2022 },
          { code: 'ASTM A82', title: 'Steel Wire for Concrete Reinforcement', year: 2020 },
          { code: 'ASTM A185', title: 'Steel Welded Wire Reinforcement', year: 2021 },
          { code: 'ASTM A240', title: 'Stainless Steel Plate & Sheet', year: 2022 },
          { code: 'ASTM A312', title: 'Seamless Stainless Steel Pipe', year: 2021 },
          { code: 'ASTM A416', title: 'Steel Strand for Prestressed Concrete', year: 2022 },
          { code: 'ASTM A500', title: 'Cold Formed Welded Carbon Steel Tubing', year: 2021 },
          { code: 'ASTM A615', title: 'Deformed & Plain Carbon Steel Bars', year: 2020 },
          { code: 'ASTM A653', title: 'Steel Sheet, Zinc Coated (Galvanized)', year: 2022 },
          { code: 'ASTM A706', title: 'Low Alloy Steel Deformed Bars', year: 2021 },
          { code: 'ASTM A820', title: 'Steel Fibers for Fiber Reinforced Concrete', year: 2021 },
          { code: 'ASTM A992', title: 'Structural Steel Shapes', year: 2020 },
          { code: 'ASTM A1011', title: 'Hot Rolled Steel Sheet', year: 2022 },
          { code: 'ASTM B88', title: 'Seamless Copper Water Tube', year: 2020 },
          { code: 'ASTM B209', title: 'Aluminum and Aluminum Alloy Sheet', year: 2021 },
          { code: 'ASTM B221', title: 'Aluminum Extruded Bar and Shapes', year: 2022 },
          { code: 'ASTM C27', title: 'Fire Clay Refractories', year: 2020 },
          { code: 'ASTM C33', title: 'Concrete Aggregates', year: 2021 },
          { code: 'ASTM C62', title: 'Building Brick (Solid)', year: 2022 },
          { code: 'ASTM C90', title: 'Load Bearing Concrete Masonry Units', year: 2021 },
          { code: 'ASTM C91', title: 'Masonry Cement', year: 2020 },
          { code: 'ASTM C94', title: 'Ready Mixed Concrete', year: 2022 },
          { code: 'ASTM C144', title: 'Aggregate for Masonry Mortar', year: 2021 },
          { code: 'ASTM C150', title: 'Portland Cement', year: 2022 },
          { code: 'ASTM C216', title: 'Facing Brick', year: 2020 },
          { code: 'ASTM C260', title: 'Air Entraining Admixtures', year: 2021 },
          { code: 'ASTM C270', title: 'Mortar for Unit Masonry', year: 2022 },
          { code: 'ASTM C309', title: 'Liquid Membrane Forming Curing Compound', year: 2021 },
          { code: 'ASTM C330', title: 'Lightweight Aggregates for Concrete', year: 2020 },
          { code: 'ASTM C494', title: 'Chemical Admixtures for Concrete', year: 2022 },
          { code: 'ASTM C503', title: 'Marble Dimension Stone', year: 2021 },
          { code: 'ASTM C552', title: 'Cellular Glass Insulation', year: 2020 },
          { code: 'ASTM C553', title: 'Mineral Fiber Blanket Insulation', year: 2022 },
          { code: 'ASTM C578', title: 'Rigid Cellular Polystyrene Insulation', year: 2021 },
          { code: 'ASTM C615', title: 'Granite Dimension Stone', year: 2020 },
          { code: 'ASTM C618', title: 'Fly Ash and Raw Calcined Pozzolan', year: 2022 },
          { code: 'ASTM C629', title: 'Slate Dimension Stone', year: 2021 },
          { code: 'ASTM C652', title: 'Hollow Brick (Hollow Masonry Units)', year: 2020 },
          { code: 'ASTM C665', title: 'Mineral Fiber Blanket for Light Frame', year: 2022 },
          { code: 'ASTM C836', title: 'High Solids Content Cold Liquid Elastomeric', year: 2021 },
          { code: 'ASTM C881', title: 'Epoxy Resin Anchors', year: 2020 },
          { code: 'ASTM C920', title: 'Elastomeric Joint Sealants', year: 2021 },
          { code: 'ASTM C926', title: 'Portland Cement Plaster', year: 2022 },
          { code: 'ASTM C936', title: 'Solid Concrete Interlocking Paving Units', year: 2020 },
          { code: 'ASTM C989', title: 'Slag Cement for Concrete', year: 2021 },
          { code: 'ASTM C1026', title: 'Ceramic Tile Specifications', year: 2022 },
          { code: 'ASTM C1107', title: 'Packaged Dry Hydraulic Cement Grout', year: 2021 },
          { code: 'ASTM C1240', title: 'Silica Fume for Concrete', year: 2020 },
          { code: 'ASTM C1289', title: 'Faced Rigid Polyisocyanurate Board', year: 2022 },
          { code: 'ASTM C1396', title: 'Gypsum Board', year: 2021 },
          { code: 'ASTM C1527', title: 'Travertine Dimension Stone', year: 2020 },
          { code: 'ASTM C1692', title: 'Autoclaved Aerated Concrete (AAC)', year: 2021 },
          { code: 'ASTM D412', title: 'Vulcanized Rubber Tension Test', year: 2020 },
          { code: 'ASTM D1190', title: 'Concrete Joint Sealer (Hot Applied)', year: 2022 },
          { code: 'ASTM D1751', title: 'Preformed Expansion Joint Fillers', year: 2021 },
          { code: 'ASTM D4434', title: 'Polyvinyl Chloride Sheet Roofing', year: 2020 },
          { code: 'ASTM D4637', title: 'EPDM Sheet Roofing', year: 2022 },
          { code: 'ASTM D4751', title: 'Apparent Opening Size of Geotextile', year: 2021 },
          { code: 'ASTM D5199', title: 'Geomembrane Thickness', year: 2020 },
          { code: 'ASTM D5324', title: 'Architectural Paints Testing', year: 2022 },
          { code: 'ASTM D5890', title: 'Bentonite Swell Index', year: 2021 },
          { code: 'ASTM D6083', title: 'Acrylic Coating for Roofing', year: 2020 },
          { code: 'ASTM D6163', title: 'SBS Modified Bituminous Sheet', year: 2022 },
          { code: 'ASTM D6222', title: 'APP Modified Bituminous Sheet', year: 2021 },
          { code: 'ASTM D6637', title: 'Geogrid Tensile Test', year: 2020 },
          { code: 'ASTM D6878', title: 'TPO Sheet Roofing', year: 2022 },
          { code: 'ASTM E84', title: 'Surface Burning Characteristics', year: 2021 },
          { code: 'ASTM E283', title: 'Air Leakage of Windows/Doors', year: 2022 },
          { code: 'ASTM E413', title: 'Sound Transmission Class (STC)', year: 2021 },
          { code: 'ASTM E119', title: 'Fire Tests of Building Construction', year: 2023 },
          { code: 'ASTM E1996', title: 'Hurricane Resistant Windows/Doors', year: 2020 },
          { code: 'ASTM E2190', title: 'Insulating Glass Unit Performance', year: 2021 },
          { code: 'ASTM F1667', title: 'Driven Fasteners for Wood', year: 2020 },
          { code: 'ASTM F1869', title: 'Moisture Vapor Emission of Concrete', year: 2021 },
          { code: 'ASTM F1700', title: 'Solid Vinyl Flooring', year: 2020 },
          { code: 'ASTM F2157', title: 'Synthetic Sports Surface', year: 2022 },
        ]
      },
      {
        body: 'NFPA', name: 'National Fire Protection Association', country: 'USA',
        standards: [
          { code: 'NFPA 1', title: 'Fire Code', year: 2021 },
          { code: 'NFPA 10', title: 'Portable Fire Extinguishers', year: 2022 },
          { code: 'NFPA 11', title: 'Foam Systems', year: 2021 },
          { code: 'NFPA 12', title: 'Carbon Dioxide Systems', year: 2020 },
          { code: 'NFPA 13', title: 'Sprinkler Systems Installation', year: 2022 },
          { code: 'NFPA 13D', title: 'Sprinkler Systems Residential', year: 2022 },
          { code: 'NFPA 13R', title: 'Sprinkler Systems Residential Occupancy', year: 2022 },
          { code: 'NFPA 14', title: 'Standpipe Systems', year: 2021 },
          { code: 'NFPA 15', title: 'Water Spray Fixed Systems', year: 2020 },
          { code: 'NFPA 16', title: 'Foam Water Sprinkler Systems', year: 2022 },
          { code: 'NFPA 17', title: 'Dry Chemical Extinguishing Systems', year: 2021 },
          { code: 'NFPA 17A', title: 'Wet Chemical Extinguishing Systems', year: 2021 },
          { code: 'NFPA 20', title: 'Stationary Fire Pumps', year: 2022 },
          { code: 'NFPA 22', title: 'Water Tanks for Fire Protection', year: 2020 },
          { code: 'NFPA 24', title: 'Private Fire Service Mains', year: 2022 },
          { code: 'NFPA 30', title: 'Flammable Liquids Code', year: 2021 },
          { code: 'NFPA 45', title: 'Laboratories Using Chemicals', year: 2020 },
          { code: 'NFPA 54', title: 'National Fuel Gas Code', year: 2021 },
          { code: 'NFPA 55', title: 'Compressed Gases & Cryogenic Fluids', year: 2020 },
          { code: 'NFPA 68', title: 'Explosion Protection by Deflagration Venting', year: 2022 },
          { code: 'NFPA 69', title: 'Explosion Prevention Systems', year: 2021 },
          { code: 'NFPA 70', title: 'National Electrical Code (NEC)', year: 2023 },
          { code: 'NFPA 70B', title: 'Electrical Equipment Maintenance', year: 2021 },
          { code: 'NFPA 72', title: 'National Fire Alarm & Signaling Code', year: 2022 },
          { code: 'NFPA 80', title: 'Fire Doors & Opening Protectives', year: 2022 },
          { code: 'NFPA 85', title: 'Boiler & Combustion Systems', year: 2021 },
          { code: 'NFPA 90A', title: 'Air Conditioning & Ventilation', year: 2021 },
          { code: 'NFPA 96', title: 'Commercial Cooking Equipment', year: 2020 },
          { code: 'NFPA 99', title: 'Health Care Facilities Code', year: 2021 },
          { code: 'NFPA 101', title: 'Life Safety Code', year: 2021 },
          { code: 'NFPA 110', title: 'Emergency & Standby Power Systems', year: 2022 },
          { code: 'NFPA 170', title: 'Standard Fire Safety Symbols', year: 2021 },
          { code: 'NFPA 2001', title: 'Clean Agent Extinguishing Systems', year: 2022 },
          { code: 'NFPA 241', title: 'Safeguarding Construction Sites', year: 2022 },
          { code: 'NFPA 502', title: 'Tunnels & Roadways Fire Protection', year: 2021 },
          { code: 'NFPA 780', title: 'Lightning Protection', year: 2020 },
          { code: 'NFPA 853', title: 'Fuel Cells Installation', year: 2020 },
          { code: 'NFPA 1142', title: 'Water Supplies for Suburban/Rural', year: 2021 },
          { code: 'NFPA 1221', title: 'Emergency Services Communications', year: 2022 },
        ]
      },
      {
        body: 'ASHRAE', name: 'American Society of Heating Refrigerating and Air Conditioning Engineers', country: 'USA',
        standards: [
          { code: 'ASHRAE 15', title: 'Refrigeration Safety', year: 2022 },
          { code: 'ASHRAE 55', title: 'Thermal Environmental Conditions', year: 2020 },
          { code: 'ASHRAE 62.1', title: 'Ventilation for Acceptable Indoor Air Quality', year: 2022 },
          { code: 'ASHRAE 62.2', title: 'Ventilation in Low Rise Residential', year: 2022 },
          { code: 'ASHRAE 90.1', title: 'Energy Standard for Buildings (Except Low Rise)', year: 2022 },
          { code: 'ASHRAE 90.2', title: 'Energy Efficient Low Rise Residential', year: 2022 },
          { code: 'ASHRAE 100', title: 'Energy Efficiency in Existing Buildings', year: 2021 },
          { code: 'ASHRAE 105', title: 'Building Energy Performance Measurement', year: 2020 },
          { code: 'ASHRAE 110', title: 'Laboratory Fume Hood Performance', year: 2021 },
          { code: 'ASHRAE 111', title: 'HVAC Duct Construction', year: 2022 },
          { code: 'ASHRAE 113', title: 'Airflow Patterns Around Buildings', year: 2020 },
          { code: 'ASHRAE 119', title: 'Air Leakage Performance for Windows', year: 2021 },
          { code: 'ASHRAE 120', title: 'Method of Test for Duct Leakage', year: 2022 },
          { code: 'ASHRAE 127', title: 'Rated Airflow of Fans', year: 2020 },
          { code: 'ASHRAE 154', title: 'Ventilation for Commercial Cooking', year: 2021 },
          { code: 'ASHRAE 161', title: 'Air Quality in Commercial Aircraft', year: 2022 },
          { code: 'ASHRAE 170', title: 'Ventilation of Health Care Facilities', year: 2021 },
          { code: 'ASHRAE 182', title: 'Skylight Fenestration Rating', year: 2020 },
          { code: 'ASHRAE 188', title: 'Legionellosis Risk Management', year: 2021 },
          { code: 'ASHRAE 189.1', title: 'High Performance Green Buildings', year: 2020 },
          { code: 'ASHRAE 201', title: 'Facility Energy Management', year: 2022 },
          { code: 'ASHRAE 202', title: 'Commissioning Process', year: 2021 },
          { code: 'ASHRAE 203', title: 'Building Energy Simulation', year: 2020 },
          { code: 'ASHRAE 514', title: 'Carbon Neutral Building Standard', year: 2023 },
          { code: 'ASHRAE 525', title: 'Net Zero Energy Buildings', year: 2023 },
        ]
      },
      {
        body: 'IEC', name: 'International Electrotechnical Commission', country: 'International',
        standards: [
          { code: 'IEC 60227', title: 'PVC Insulated Cables', year: 2022 },
          { code: 'IEC 60228', title: 'Conductors of Insulated Cables', year: 2021 },
          { code: 'IEC 60331', title: 'Fire Resistant Cable Circuits', year: 2022 },
          { code: 'IEC 60335', title: 'Household Appliance Safety', year: 2021 },
          { code: 'IEC 60364', title: 'Low Voltage Electrical Installations', year: 2022 },
          { code: 'IEC 60445', title: 'Equipment Terminal Identification', year: 2021 },
          { code: 'IEC 60502', title: 'Power Cables (Extruded Insulation)', year: 2022 },
          { code: 'IEC 60529', title: 'Degrees of Protection (IP Code)', year: 2021 },
          { code: 'IEC 60598', title: 'Luminaires (Lighting)', year: 2022 },
          { code: 'IEC 60669', title: 'Switches for Household Installations', year: 2021 },
          { code: 'IEC 60715', title: 'DIN Rail Dimensions', year: 2020 },
          { code: 'IEC 60898', title: 'MCB (Miniature Circuit Breakers)', year: 2022 },
          { code: 'IEC 60947', title: 'Low Voltage Switchgear', year: 2021 },
          { code: 'IEC 61008', title: 'RCCB (Residual Current Breakers)', year: 2022 },
          { code: 'IEC 61009', title: 'RCBO (Residual Current MCB)', year: 2021 },
          { code: 'IEC 61084', title: 'Cable Trunking Systems', year: 2020 },
          { code: 'IEC 61386', title: 'Conduit Systems for Cable Management', year: 2022 },
          { code: 'IEC 61439', title: 'Low Voltage Switchgear & Controlgear', year: 2021 },
          { code: 'IEC 61537', title: 'Cable Tray Systems', year: 2022 },
          { code: 'IEC 61800', title: 'Adjustable Speed Electrical Drives', year: 2021 },
          { code: 'IEC 62040', title: 'UPS (Uninterruptible Power Systems)', year: 2022 },
          { code: 'IEC 62301', title: 'Standby Power Measurement', year: 2021 },
          { code: 'IEC 62471', title: 'Photobiological Safety of Lamps', year: 2022 },
          { code: 'IEC 62930', title: 'DC Cables for Photovoltaic Systems', year: 2021 },
        ]
      },
      {
        body: 'ISO', name: 'International Organization for Standardization', country: 'International',
        standards: [
          { code: 'ISO 140', title: 'Acoustics - Measurement of Sound Insulation', year: 2021 },
          { code: 'ISO 2531', title: 'Ductile Iron Pipes', year: 2022 },
          { code: 'ISO 4064', title: 'Water Meters', year: 2021 },
          { code: 'ISO 4427', title: 'PE Pipes for Water Supply', year: 2022 },
          { code: 'ISO 4435', title: 'PVC U Pipes for Sewerage', year: 2021 },
          { code: 'ISO 630', title: 'Structural Steels', year: 2020 },
          { code: 'ISO 7628', title: 'Road Vehicle Thermoplastics Tubing', year: 2021 },
          { code: 'ISO 834', title: 'Fire Resistance Tests', year: 2022 },
          { code: 'ISO 9001', title: 'Quality Management Systems', year: 2015 },
          { code: 'ISO 1000', title: 'SI Units', year: 2021 },
          { code: 'ISO 14001', title: 'Environmental Management Systems', year: 2015 },
          { code: 'ISO 1452', title: 'PVC U Pipes for Water Supply', year: 2022 },
          { code: 'ISO 1461', title: 'Hot Dip Galvanized Coatings', year: 2022 },
          { code: 'ISO 20653', title: 'Road Vehicles - IP Protection Classes', year: 2021 },
          { code: 'ISO 45001', title: 'Occupational Health & Safety', year: 2018 },
          { code: 'ISO 50001', title: 'Energy Management Systems', year: 2018 },
          { code: 'ISO 6789', title: 'Torque Tools', year: 2020 },
          { code: 'ISO 6946', title: 'Building Thermal Resistance', year: 2022 },
          { code: 'ISO 717', title: 'Sound Insulation Rating', year: 2021 },
          { code: 'ISO 7730', title: 'Thermal Comfort', year: 2022 },
          { code: 'ISO 898', title: 'Mechanical Properties of Fasteners', year: 2021 },
          { code: 'ISO 9227', title: 'Salt Spray Corrosion Test', year: 2022 },
          { code: 'ISO 9241', title: 'Ergonomics of Human System Interaction', year: 2021 },
          { code: 'ISO 9869', title: 'Thermal Insulation In Situ Measurements', year: 2022 },
          { code: 'ISO 10211', title: 'Thermal Bridges', year: 2020 },
          { code: 'ISO 10456', title: 'Thermal Properties of Materials', year: 2021 },
          { code: 'ISO 10848', title: 'Acoustic Flanking Transmission', year: 2020 },
          { code: 'ISO 11654', title: 'Sound Absorption Rating', year: 2021 },
          { code: 'ISO 11855', title: 'Radiant Heating and Cooling', year: 2022 },
          { code: 'ISO 11925', title: 'Reaction to Fire Tests', year: 2021 },
          { code: 'ISO 12241', title: 'Thermal Insulation of Equipment', year: 2022 },
          { code: 'ISO 12567', title: 'Thermal Performance of Windows', year: 2021 },
          { code: 'ISO 12676', title: 'Aluminum Windows - Air Permeability', year: 2020 },
          { code: 'ISO 12944', title: 'Corrosion Protection by Coatings', year: 2022 },
          { code: 'ISO 13370', title: 'Thermal Performance of Ground Floors', year: 2021 },
          { code: 'ISO 13786', title: 'Thermal Mass Properties', year: 2022 },
          { code: 'ISO 13788', title: 'Hygrothermal Performance of Components', year: 2021 },
          { code: 'ISO 13790', title: 'Energy Use for Heating and Cooling', year: 2020 },
          { code: 'ISO 14683', title: 'Thermal Bridges in Building', year: 2022 },
          { code: 'ISO 15099', title: 'Thermal Performance of Windows', year: 2021 },
          { code: 'ISO 15686', title: 'Service Life of Buildings', year: 2022 },
          { code: 'ISO 15927', title: 'Climatic Data for Building Design', year: 2021 },
          { code: 'ISO 16757', title: 'BIM Product Data', year: 2022 },
          { code: 'ISO 16813', title: 'Indoor Environment Design', year: 2021 },
          { code: 'ISO 19650', title: 'BIM Information Management', year: 2018 },
          { code: 'ISO 52000', title: 'Energy Performance of Buildings', year: 2022 },
          { code: 'ISO 52003', title: 'Energy Performance Indicators', year: 2021 },
          { code: 'ISO 52010', title: 'Climate Data for Energy Calculations', year: 2022 },
          { code: 'ISO 52016', title: 'Energy Calculation Methods', year: 2021 },
          { code: 'ISO 52018', title: 'Energy Performance Certification', year: 2022 },
        ]
      },
      {
        body: 'BS', name: 'British Standards', country: 'UK',
        standards: [
          { code: 'BS 3', title: 'Portable Fire Extinguishers', year: 2024 },
          { code: 'BS 26', title: 'Gas Water Heaters', year: 2020 },
          { code: 'BS 188', title: 'Methods of Testing Soils', year: 2022 },
          { code: 'BS 235', title: 'Wallpaper Specifications', year: 2021 },
          { code: 'BS 449', title: 'Steel in Building', year: 2020 },
          { code: 'BS 476', title: 'Fire Tests on Building Materials', year: 2022 },
          { code: 'BS 545', title: 'Ductile Iron Pipes (Water)', year: 2020 },
          { code: 'BS 595', title: 'Fire Tests for Roofing', year: 2022 },
          { code: 'BS 648', title: 'Schedule of Weights', year: 2021 },
          { code: 'BS 665', title: 'Protection of Structures against Lightning', year: 2022 },
          { code: 'BS 750', title: 'Fire Hydrants', year: 2020 },
          { code: 'BS 882', title: 'Aggregates for Concrete', year: 2021 },
          { code: 'BS 1088', title: 'Marine Plywood', year: 2020 },
          { code: 'BS 1192', title: 'Construction Drawing Practice', year: 2022 },
          { code: 'BS 1243', title: 'Wall Ties', year: 2021 },
          { code: 'BS 1363', title: '13A Plugs and Sockets', year: 2022 },
          { code: 'BS 1377', title: 'Methods of Test for Soils', year: 2020 },
          { code: 'BS 1881', title: 'Testing Concrete', year: 2021 },
          { code: 'BS 4449', title: 'Steel Bars for Concrete Reinforcement', year: 2022 },
          { code: 'BS 4482', title: 'Steel Wire for Concrete Reinforcement', year: 2021 },
          { code: 'BS 4483', title: 'Steel Fabric for Concrete Reinforcement', year: 2020 },
          { code: 'BS 5246', title: 'Plastic Pipes for Drainage', year: 2021 },
          { code: 'BS 5262', title: 'External Renderings', year: 2020 },
          { code: 'BS 5328', title: 'Concrete (Withdrawn, replaced by BS EN 206)', year: 2021 },
          { code: 'BS 5492', title: 'Gypsum Plasterboard', year: 2022 },
          { code: 'BS 5588', title: 'Fire Safety in Buildings', year: 2020 },
          { code: 'BS 5628', title: 'Masonry Design Code', year: 2021 },
          { code: 'BS 5837', title: 'Trees in Relation to Construction', year: 2022 },
          { code: 'BS 5839', title: 'Fire Detection & Alarm Systems', year: 2021 },
          { code: 'BS 5896', title: 'Prestressing Steel', year: 2020 },
          { code: 'BS 5950', title: 'Structural Steel Design', year: 2022 },
          { code: 'BS 5975', title: 'Temporary Works', year: 2021 },
          { code: 'BS 6073', title: 'Precast Concrete Masonry', year: 2020 },
          { code: 'BS 6100', title: 'Building & Civil Engineering Vocabulary', year: 2022 },
          { code: 'BS 6180', title: 'Barriers in Buildings', year: 2021 },
          { code: 'BS 6229', title: 'Flat Roofs with Continuous Coverings', year: 2022 },
          { code: 'BS 6262', title: 'Glazing for Buildings', year: 2021 },
          { code: 'BS 6349', title: 'Maritime Structures', year: 2020 },
          { code: 'BS 6399', title: 'Loading for Buildings', year: 2021 },
          { code: 'BS 6465', title: 'Sanitary Installations', year: 2022 },
          { code: 'BS 6485', title: 'Clay Drainage Pipes', year: 2021 },
          { code: 'BS 6700', title: 'Water Supply Installations', year: 2020 },
          { code: 'BS 6742', title: 'Electrostatic Spray Coating', year: 2021 },
          { code: 'BS 6910', title: 'Firefighting Equipment', year: 2022 },
          { code: 'BS 6920', title: 'Materials in Contact with Water', year: 2021 },
          { code: 'BS 6945', title: 'Suspended Ceiling Systems', year: 2020 },
          { code: 'BS 7000', title: 'Design Management Systems', year: 2022 },
          { code: 'BS 7208', title: 'Thermal Insulation of Ducts', year: 2021 },
          { code: 'BS 7371', title: 'Coatings for Fasteners', year: 2020 },
          { code: 'BS 743', title: 'Damp Proof Courses', year: 2022 },
          { code: 'BS 7543', title: 'Durability of Buildings', year: 2021 },
          { code: 'BS 7671', title: 'IET Wiring Regulations', year: 2022 },
          { code: 'BS 8000', title: 'Workmanship on Building Sites', year: 2021 },
          { code: 'BS 8004', title: 'Foundation Design', year: 2020 },
          { code: 'BS 8102', title: 'Waterproofing of Below Ground Structures', year: 2022 },
          { code: 'BS 8110', title: 'Structural Concrete Design', year: 2021 },
          { code: 'BS 8200', title: 'Design of Non Load Bearing Partitions', year: 2020 },
          { code: 'BS 8206', title: 'Lighting for Buildings', year: 2022 },
          { code: 'BS 8210', title: 'Facility Management', year: 2021 },
          { code: 'BS 8215', title: 'Design of Hot Water Systems', year: 2020 },
          { code: 'BS 8220', title: 'Security of Buildings', year: 2022 },
          { code: 'BS 8233', title: 'Sound Insulation in Buildings', year: 2021 },
          { code: 'BS 8290', title: 'Suspended Ceilings', year: 2020 },
          { code: 'BS 8298', title: 'Stone Cladding', year: 2022 },
          { code: 'BS 8300', title: 'Accessible Buildings', year: 2021 },
          { code: 'BS 845', title: 'Boiler Efficiency', year: 2022 },
          { code: 'BS 8489', title: 'Water Mist Systems', year: 2021 },
          { code: 'BS 8494', title: 'Electronic Fire Detection', year: 2020 },
          { code: 'BS 8519', title: 'Fire Cables in Buildings', year: 2021 },
          { code: 'BS 8538', title: 'Fire Alarm Monitoring', year: 2022 },
          { code: 'BS 8587', title: 'Fire Risk Assessment', year: 2021 },
          { code: 'BS 8590', title: 'Emergency Lighting Systems', year: 2020 },
          { code: 'BS 8611', title: 'Ventilation Duct Cleaning', year: 2022 },
          { code: 'BS 8644', title: 'Smart Buildings', year: 2023 },
          { code: 'BS 9251', title: 'Residential Sprinkler Systems', year: 2021 },
          { code: 'BS 9266', title: 'Design of Accessible Housing', year: 2022 },
          { code: 'BS 9345', title: 'Modern Methods of Construction', year: 2023 },
          { code: 'BS 9990', title: 'Non Automatic Fire Fighting Systems', year: 2021 },
          { code: 'BS 9991', title: 'Fire Safety in Residential Buildings', year: 2022 },
          { code: 'BS 9992', title: 'Fire Safety for Transport Infrastructure', year: 2021 },
          { code: 'BS 9999', title: 'Fire Safety in Non Residential Buildings', year: 2022 },
        ]
      },
      {
        body: 'EN', name: 'European Norms', country: 'Europe',
        standards: [
          { code: 'EN 197-1', title: 'Cement - Composition & Specifications', year: 2021 },
          { code: 'EN 206', title: 'Concrete - Specification & Performance', year: 2022 },
          { code: 'EN 459-1', title: 'Building Lime', year: 2021 },
          { code: 'EN 490', title: 'Concrete Roofing Tiles', year: 2020 },
          { code: 'EN 681-1', title: 'Elastomeric Seals for Water Pipes', year: 2022 },
          { code: 'EN 771-1', title: 'Clay Masonry Units', year: 2021 },
          { code: 'EN 771-2', title: 'Calcium Silicate Masonry Units', year: 2020 },
          { code: 'EN 771-3', title: 'Aggregate Concrete Masonry Units', year: 2022 },
          { code: 'EN 771-4', title: 'Autoclaved Aerated Concrete Units', year: 2021 },
          { code: 'EN 845-1', title: 'Wall Ties', year: 2020 },
          { code: 'EN 933', title: 'Aggregate Geometrical Properties', year: 2021 },
          { code: 'EN 934-2', title: 'Concrete Admixtures', year: 2022 },
          { code: 'EN 988', title: 'Zinc Sheet for Roofing', year: 2021 },
          { code: 'EN 993', title: 'Dense Shaped Refractories', year: 2020 },
          { code: 'EN 998-1', title: 'Masonry Mortar Specifications', year: 2022 },
          { code: 'EN 998-2', title: 'Masonry Mortar Test Methods', year: 2021 },
          { code: 'EN 1008', title: 'Mixing Water for Concrete', year: 2020 },
          { code: 'EN 1057', title: 'Copper Tubes for Water', year: 2022 },
          { code: 'EN 1090', title: 'Steel & Aluminum Structures', year: 2021 },
          { code: 'EN 1990', title: 'Eurocode 0 - Basis of Structural Design', year: 2022 },
          { code: 'EN 1991', title: 'Eurocode 1 - Actions on Structures', year: 2022 },
          { code: 'EN 1992', title: 'Eurocode 2 - Concrete Structures', year: 2022 },
          { code: 'EN 1993', title: 'Eurocode 3 - Steel Structures', year: 2022 },
          { code: 'EN 1994', title: 'Eurocode 4 - Composite Structures', year: 2022 },
          { code: 'EN 1995', title: 'Eurocode 5 - Timber Structures', year: 2022 },
          { code: 'EN 1996', title: 'Eurocode 6 - Masonry Structures', year: 2022 },
          { code: 'EN 1997', title: 'Eurocode 7 - Geotechnical Design', year: 2022 },
          { code: 'EN 1998', title: 'Eurocode 8 - Seismic Design', year: 2022 },
          { code: 'EN 1999', title: 'Eurocode 9 - Aluminum Structures', year: 2022 },
          { code: 'EN 10025', title: 'Hot Rolled Steel Structural Products', year: 2022 },
          { code: 'EN 10130', title: 'Cold Rolled Steel Sheet', year: 2021 },
          { code: 'EN 10223', title: 'Steel Wire Fencing', year: 2020 },
          { code: 'EN 10255', title: 'Steel Tubes for Water', year: 2022 },
          { code: 'EN 10346', title: 'Continuous Hot Dip Coated Steel', year: 2021 },
          { code: 'EN 12201', title: 'PE Pipes for Water Supply', year: 2022 },
          { code: 'EN 12259', title: 'Sprinkler Components', year: 2021 },
          { code: 'EN 12334', title: 'Check Valves', year: 2020 },
          { code: 'EN 124', title: 'Manhole Covers', year: 2022 },
          { code: 'EN 12608', title: 'UPVC Profiles for Windows/Doors', year: 2021 },
          { code: 'EN 12825', title: 'Raised Access Floors', year: 2020 },
          { code: 'EN 12845', title: 'Fixed Firefighting Systems - Sprinklers', year: 2022 },
          { code: 'EN 12975', title: 'Solar Thermal Collectors', year: 2021 },
          { code: 'EN 13055', title: 'Lightweight Aggregates', year: 2020 },
          { code: 'EN 13108', title: 'Asphalt Mixtures', year: 2022 },
          { code: 'EN 13162', title: 'Mineral Wool Insulation', year: 2021 },
          { code: 'EN 13163', title: 'EPS Insulation', year: 2020 },
          { code: 'EN 13164', title: 'XPS Insulation', year: 2022 },
          { code: 'EN 13165', title: 'PUR/PIR Insulation', year: 2021 },
          { code: 'EN 13166', title: 'Phenolic Foam Insulation', year: 2020 },
          { code: 'EN 13167', title: 'Cellular Glass Insulation', year: 2022 },
          { code: 'EN 13180', title: 'Flexible Ducting for HVAC', year: 2021 },
          { code: 'EN 13238', title: 'Fire Reaction of Building Materials', year: 2020 },
          { code: 'EN 13241', title: 'Industrial Doors & Gates', year: 2022 },
          { code: 'EN 13251', title: 'Geotextiles for Earthworks', year: 2021 },
          { code: 'EN 13279', title: 'Gypsum Plasters', year: 2020 },
          { code: 'EN 13280', title: 'GRP Water Tanks', year: 2022 },
          { code: 'EN 13300', title: 'Paints & Varnishes', year: 2021 },
          { code: 'EN 13318', title: 'Screed Material & Floorings', year: 2020 },
          { code: 'EN 13329', title: 'Laminate Flooring', year: 2022 },
          { code: 'EN 1338', title: 'Concrete Paving Blocks', year: 2021 },
          { code: 'EN 1340', title: 'Concrete Kerbs', year: 2020 },
          { code: 'EN 13476', title: 'Structured Wall Plastic Pipes', year: 2022 },
          { code: 'EN 13480', title: 'Metallic Industrial Piping', year: 2021 },
          { code: 'EN 13491', title: 'Geosynthetic Barriers', year: 2020 },
          { code: 'EN 13501', title: 'Fire Classification of Construction Products', year: 2022 },
          { code: 'EN 13598', title: 'Plastic Manholes & Inspection Chambers', year: 2021 },
          { code: 'EN 13618', title: 'Flexible Hose Connectors', year: 2020 },
          { code: 'EN 13707', title: 'Bitumen Membranes for Roofing', year: 2022 },
          { code: 'EN 13748', title: 'Terrazzo Tiles', year: 2021 },
          { code: 'EN 13830', title: 'Curtain Walling', year: 2022 },
          { code: 'EN 13831', title: 'Pressure Vessels', year: 2021 },
          { code: 'EN 13956', title: 'Plastic & Rubber Roofing Membranes', year: 2020 },
          { code: 'EN 13964', title: 'Suspended Ceilings', year: 2022 },
          { code: 'EN 13986', title: 'Wood Based Panels', year: 2021 },
          { code: 'EN 1401', title: 'PVC U Pipes for Sewerage', year: 2022 },
          { code: 'EN 14080', title: 'Glulam Timber Structures', year: 2021 },
          { code: 'EN 14081', title: 'Strength Graded Structural Timber', year: 2020 },
          { code: 'EN 14153', title: 'Diving Services', year: 2021 },
          { code: 'EN 14188', title: 'Joint Sealants', year: 2022 },
          { code: 'EN 14315', title: 'Spray Polyurethane Foam', year: 2021 },
          { code: 'EN 14339', title: 'Underground Fire Hydrants', year: 2020 },
          { code: 'EN 14342', title: 'Wood Flooring', year: 2022 },
          { code: 'EN 14351', title: 'Windows & Doors', year: 2021 },
          { code: 'EN 14384', title: 'Pillar Fire Hydrants', year: 2020 },
          { code: 'EN 14411', title: 'Ceramic Tiles', year: 2022 },
          { code: 'EN 14511', title: 'Air Conditioners & Heat Pumps', year: 2021 },
          { code: 'EN 1452', title: 'PVC U Pipes for Water', year: 2022 },
          { code: 'EN 14617', title: 'Agglomerated Stone', year: 2020 },
          { code: 'EN 14704', title: 'Expansion Joints for Piping', year: 2021 },
          { code: 'EN 14825', title: 'VRF & Heat Pump Performance', year: 2022 },
          { code: 'EN 14889', title: 'Fibers for Concrete', year: 2021 },
          { code: 'EN 14904', title: 'Sports Flooring', year: 2020 },
          { code: 'EN 1504', title: 'Concrete Protection & Repair', year: 2022 },
          { code: 'EN 1505', title: 'HVAC Duct Dimensions', year: 2021 },
          { code: 'EN 1507', title: 'Ductwork Strength & Leakage', year: 2020 },
          { code: 'EN 15167', title: 'GGBS for Concrete', year: 2022 },
          { code: 'EN 15650', title: 'Fire Dampers for HVAC', year: 2021 },
          { code: 'EN 15651', title: 'Joint Sealants for Non Structural Use', year: 2020 },
          { code: 'EN 15814', title: 'Liquid Applied Waterproofing', year: 2022 },
          { code: 'EN 16069', title: 'Acoustic Foam Materials', year: 2021 },
          { code: 'EN 16809', title: 'Aerogel Insulation', year: 2022 },
          { code: 'EN 17416', title: 'Timber Structures - Design', year: 2023 },
          { code: 'EN 17417', title: 'Carbon Accounting in Construction', year: 2023 },
          { code: 'EN 1796', title: 'GRP Pipes for Water', year: 2021 },
          { code: 'EN 1916', title: 'Concrete Pipes & Fittings', year: 2022 },
          { code: 'EN 1917', title: 'Precast Manholes', year: 2021 },
          { code: 'EN 50085', title: 'Cable Trunking Systems', year: 2020 },
          { code: 'EN 50173', title: 'Generic Cabling Systems', year: 2022 },
          { code: 'EN 50194', title: 'Gas Detectors for Domestic', year: 2021 },
          { code: 'EN 50291', title: 'CO Detectors for Domestic', year: 2020 },
        ]
      },
      {
        body: 'SASO', name: 'Saudi Standards, Metrology and Quality Organization', country: 'Saudi Arabia',
        standards: [
          { code: 'SASO 2379', title: 'Portland Cement Specifications', year: 2021 },
          { code: 'SASO 2853', title: 'Steel Rebar Standards', year: 2022 },
          { code: 'SASO 2888', title: 'Electrical Cable Standards', year: 2021 },
          { code: 'SASO 2890', title: 'Water Pipe Standards', year: 2022 },
          { code: 'SASO 2915', title: 'PVC Conduit Standards', year: 2020 },
          { code: 'SASO 2920', title: 'Fire Alarm Equipment', year: 2021 },
          { code: 'SASO 2940', title: 'Lighting Efficiency Standards', year: 2022 },
          { code: 'SASO 2955', title: 'HVAC Efficiency Standards', year: 2022 },
          { code: 'SASO 2965', title: 'Ceramic Tile Specifications', year: 2021 },
          { code: 'SASO 2970', title: 'Insulation Material Standards', year: 2020 },
          { code: 'SASO 2980', title: 'Window & Door Performance', year: 2022 },
          { code: 'SASO 2999', title: 'Water Tank Standards', year: 2021 },
          { code: 'SASO 3010', title: 'Steel Structure Standards', year: 2022 },
          { code: 'SASO 3020', title: 'Plastic Piping Systems', year: 2020 },
          { code: 'SASO 3030', title: 'Fire Extinguisher Standards', year: 2021 },
          { code: 'SASO 3040', title: 'Elevator Safety Standards', year: 2022 },
          { code: 'SASO 3050', title: 'Building Thermal Insulation', year: 2021 },
          { code: 'SASO EAS 2013', title: 'Electrical Appliances Energy Labeling', year: 2023 },
          { code: 'SASO EAS 2014', title: 'Air Conditioner Energy Labeling', year: 2023 },
          { code: 'SASO 2663', title: 'Energy Efficiency for Buildings', year: 2021 },
        ]
      },
      {
        body: 'DIN', name: 'Deutsches Institut für Normung', country: 'Germany',
        standards: [
          { code: 'DIN 1045', title: 'Concrete Structures', year: 2021 },
          { code: 'DIN 1053', title: 'Masonry Structures', year: 2020 },
          { code: 'DIN 1055', title: 'Actions on Structures', year: 2022 },
          { code: 'DIN 18015', title: 'Electrical Installations in Buildings', year: 2020 },
          { code: 'DIN 18040', title: 'Barrier Free Construction', year: 2021 },
          { code: 'DIN 18065', title: 'Stairs in Buildings', year: 2022 },
          { code: 'DIN 18195', title: 'Waterproofing of Buildings', year: 2021 },
          { code: 'DIN 18202', title: 'Tolerances in Building Construction', year: 2020 },
          { code: 'DIN 18230', title: 'Fire Protection', year: 2022 },
          { code: 'DIN 18234', title: 'Fire Resisting Glazing', year: 2021 },
          { code: 'DIN 18330', title: 'Dry Mortar', year: 2020 },
          { code: 'DIN 18331', title: 'Concrete & Reinforced Concrete Works', year: 2022 },
          { code: 'DIN 18332', title: 'Natural Stone Works', year: 2021 },
          { code: 'DIN 18333', title: 'Cast Stone Works', year: 2020 },
          { code: 'DIN 18334', title: 'Wood & Timber Works', year: 2022 },
          { code: 'DIN 18335', title: 'Steel Construction Works', year: 2021 },
          { code: 'DIN 18336', title: 'Waterproofing Works', year: 2020 },
          { code: 'DIN 18338', title: 'Roofing & Roof Waterproofing', year: 2022 },
          { code: 'DIN 18339', title: 'Pipe Installation', year: 2021 },
          { code: 'DIN 18340', title: 'Drywall Construction', year: 2020 },
          { code: 'DIN 18350', title: 'Plastering', year: 2022 },
          { code: 'DIN 18351', title: 'Curtain Walling', year: 2021 },
          { code: 'DIN 18353', title: 'Flooring Works', year: 2020 },
          { code: 'DIN 18354', title: 'Tiling Works', year: 2022 },
          { code: 'DIN 18355', title: 'Joinery Works', year: 2021 },
          { code: 'DIN 18356', title: 'Painting & Coating', year: 2020 },
          { code: 'DIN 18357', title: 'Metal Works', year: 2022 },
          { code: 'DIN 18358', title: 'Glass Works', year: 2021 },
          { code: 'DIN 18360', title: 'Electrical Installations', year: 2020 },
          { code: 'DIN 18361', title: 'HVAC Systems', year: 2022 },
          { code: 'DIN 18362', title: 'Gas & Water Installations', year: 2021 },
          { code: 'DIN 18363', title: 'Fire Protection Systems', year: 2020 },
          { code: 'DIN 18364', title: 'Elevator Systems', year: 2022 },
          { code: 'DIN 18365', title: 'Floor Coverings', year: 2021 },
          { code: 'DIN 18451', title: 'Scaffolding', year: 2020 },
          { code: 'DIN 18531', title: 'Flat Roof Waterproofing', year: 2022 },
          { code: 'DIN 18533', title: 'Below Grade Waterproofing', year: 2021 },
          { code: 'DIN 18534', title: 'Internal Waterproofing', year: 2020 },
          { code: 'DIN 18535', title: 'Waterproofing of Swimming Pools', year: 2022 },
          { code: 'DIN 4102', title: 'Fire Behaviour of Materials', year: 2021 },
          { code: 'DIN 4108', title: 'Thermal Insulation in Buildings', year: 2022 },
          { code: 'DIN 4109', title: 'Sound Insulation in Buildings', year: 2021 },
          { code: 'DIN 5035', title: 'Interior Lighting', year: 2020 },
          { code: 'DIN 77400', title: 'Cleaning of Buildings', year: 2022 },
          { code: 'DIN EN 14351', title: 'Windows & Doors (German Adoption)', year: 2021 },
          { code: 'DIN VDE 0100', title: 'Low Voltage Installations', year: 2022 },
          { code: 'DIN VDE 0105', title: 'Operation of Electrical Installations', year: 2021 },
          { code: 'DIN VDE 0606', title: 'Electrical Connector Boxes', year: 2020 },
          { code: 'DIN VDE 0623', title: 'Plugs & Sockets', year: 2022 },
          { code: 'DIN VDE 0660', title: 'Switchgear', year: 2021 },
          { code: 'DIN 8074', title: 'PE Pipes Dimensions', year: 2021 },
          { code: 'DIN 8075', title: 'PE Pipes Quality', year: 2020 },
          { code: 'DIN 8078', title: 'PP Pipes', year: 2022 },
          { code: 'DIN 16962', title: 'PVC Pipes', year: 2021 },
        ]
      },
      {
        body: 'UL', name: 'Underwriters Laboratories', country: 'USA',
        standards: [
          { code: 'UL 10', title: 'Fire Tests of Door Assemblies', year: 2022 },
          { code: 'UL 38', title: 'Manual Signaling Boxes', year: 2020 },
          { code: 'UL 199', title: 'Automatic Sprinklers', year: 2022 },
          { code: 'UL 217', title: 'Smoke Alarms', year: 2021 },
          { code: 'UL 260', title: 'Deluge Valves', year: 2020 },
          { code: 'UL 268', title: 'Smoke Detectors for Fire Alarm', year: 2022 },
          { code: 'UL 464', title: 'Audible Signaling Devices', year: 2021 },
          { code: 'UL 521', title: 'Heat Detectors', year: 2020 },
          { code: 'UL 555', title: 'Fire Dampers', year: 2022 },
          { code: 'UL 555S', title: 'Smoke Dampers', year: 2021 },
          { code: 'UL 710', title: 'Exhaust Hoods', year: 2020 },
          { code: 'UL 723', title: 'Surface Burning Characteristics', year: 2022 },
          { code: 'UL 762', title: 'Gas Venting', year: 2021 },
          { code: 'UL 864', title: 'Fire Alarm Control Units', year: 2022 },
          { code: 'UL 924', title: 'Emergency Lighting', year: 2021 },
          { code: 'UL 1042', title: 'Electric Baseboard Heaters', year: 2020 },
          { code: 'UL 1411', title: 'ESFR Sprinklers', year: 2022 },
          { code: 'UL 1480', title: 'Speakers for Fire Alarm', year: 2021 },
          { code: 'UL 1484', title: 'Gas Detectors', year: 2020 },
          { code: 'UL 1626', title: 'Residential Sprinklers', year: 2022 },
          { code: 'UL 1730', title: 'Smoke Alarm Monitors', year: 2021 },
          { code: 'UL 1971', title: 'Signaling for Hearing Impaired', year: 2020 },
          { code: 'UL 2034', title: 'CO Alarms', year: 2022 },
          { code: 'UL 2075', title: 'Refrigerant Detectors', year: 2021 },
          { code: 'UL 2079', title: 'Firestop Systems', year: 2020 },
          { code: 'UL 2129', title: 'Halocarbon Clean Agent Extinguishing', year: 2022 },
        ]
      },
      {
        body: 'BS EN', name: 'British Standards adopting European Norms', country: 'UK',
        standards: [
          { code: 'BS EN 197-1', title: 'Cement Composition', year: 2021 },
          { code: 'BS EN 206', title: 'Concrete Specification', year: 2022 },
          { code: 'BS EN 459-1', title: 'Building Lime', year: 2021 },
          { code: 'BS EN 545', title: 'Ductile Iron Pipes', year: 2020 },
          { code: 'BS EN 681-1', title: 'Elastomeric Pipe Seals', year: 2022 },
          { code: 'BS EN 771-1', title: 'Clay Masonry Units', year: 2021 },
          { code: 'BS EN 845-1', title: 'Wall Ties', year: 2020 },
          { code: 'BS EN 934-2', title: 'Admixtures for Concrete', year: 2022 },
          { code: 'BS EN 988', title: 'Zinc for Roofing', year: 2021 },
          { code: 'BS EN 998-1', title: 'Mortar Specifications', year: 2020 },
          { code: 'BS EN 1057', title: 'Copper Pipes', year: 2022 },
          { code: 'BS EN 1090-1', title: 'CE Marking of Steel Structures', year: 2021 },
          { code: 'BS EN 1090-2', title: 'Execution of Steel Structures', year: 2020 },
          { code: 'BS EN 1990', title: 'Eurocode 0 Basis of Design', year: 2022 },
          { code: 'BS EN 1991', title: 'Eurocode 1 Actions', year: 2022 },
          { code: 'BS EN 1992', title: 'Eurocode 2 Concrete', year: 2022 },
          { code: 'BS EN 1993', title: 'Eurocode 3 Steel', year: 2022 },
          { code: 'BS EN 1994', title: 'Eurocode 4 Composite', year: 2022 },
          { code: 'BS EN 1995', title: 'Eurocode 5 Timber', year: 2022 },
          { code: 'BS EN 1996', title: 'Eurocode 6 Masonry', year: 2022 },
          { code: 'BS EN 1997', title: 'Eurocode 7 Geotechnical', year: 2022 },
          { code: 'BS EN 1998', title: 'Eurocode 8 Seismic', year: 2022 },
          { code: 'BS EN 1999', title: 'Eurocode 9 Aluminum', year: 2022 },
          { code: 'BS EN 10025', title: 'Hot Rolled Steel', year: 2021 },
          { code: 'BS EN 10130', title: 'Cold Rolled Steel', year: 2020 },
          { code: 'BS EN 10216', title: 'Seamless Steel Tubes', year: 2022 },
          { code: 'BS EN 10217', title: 'Welded Steel Tubes', year: 2021 },
          { code: 'BS EN 10346', title: 'Galvanized Steel Sheet', year: 2020 },
          { code: 'BS EN 12201', title: 'PE Pipes Water Supply', year: 2022 },
          { code: 'BS EN 12259', title: 'Sprinkler Components', year: 2021 },
          { code: 'BS EN 124', title: 'Manhole Covers', year: 2022 },
          { code: 'BS EN 12608', title: 'UPVC Windows', year: 2021 },
          { code: 'BS EN 12825', title: 'Raised Access Floors', year: 2020 },
          { code: 'BS EN 12845', title: 'Sprinkler Systems', year: 2022 },
          { code: 'BS EN 13162-67', title: 'Insulation Product Standards', year: 2021 },
          { code: 'BS EN 13241', title: 'Industrial Doors', year: 2022 },
          { code: 'BS EN 13279', title: 'Gypsum Plasters', year: 2021 },
          { code: 'BS EN 13300', title: 'Paints & Varnishes Classification', year: 2020 },
          { code: 'BS EN 13480', title: 'Metallic Piping', year: 2022 },
          { code: 'BS EN 13501', title: 'Fire Classification', year: 2021 },
          { code: 'BS EN 13748', title: 'Terrazzo Tiles', year: 2020 },
          { code: 'BS EN 13830', title: 'Curtain Walling', year: 2022 },
          { code: 'BS EN 13956', title: 'Roofing Membranes', year: 2021 },
          { code: 'BS EN 13964', title: 'Suspended Ceilings', year: 2020 },
          { code: 'BS EN 14080', title: 'Glulam', year: 2022 },
          { code: 'BS EN 14342', title: 'Wood Flooring', year: 2021 },
          { code: 'BS EN 14411', title: 'Ceramic Tiles', year: 2022 },
          { code: 'BS EN 14511', title: 'AC & Heat Pumps', year: 2021 },
          { code: 'BS EN 1504', title: 'Concrete Repair', year: 2022 },
          { code: 'BS EN 15650', title: 'Fire Dampers', year: 2021 },
          { code: 'BS EN 50173', title: 'Cabling Installations', year: 2022 },
          { code: 'BS EN 50291', title: 'CO Detectors', year: 2021 },
          { code: 'BS EN 60079', title: 'Explosive Atmospheres', year: 2022 },
          { code: 'BS EN 60228', title: 'Cable Conductors', year: 2021 },
          { code: 'BS EN 60335', title: 'Appliance Safety', year: 2022 },
          { code: 'BS EN 60529', title: 'IP Ratings', year: 2021 },
          { code: 'BS EN 60598', title: 'Luminaires', year: 2022 },
          { code: 'BS EN 60898', title: 'MCBs', year: 2021 },
          { code: 'BS EN 60947', title: 'Switchgear', year: 2022 },
          { code: 'BS EN 61008', title: 'RCCBs', year: 2021 },
          { code: 'BS EN 61386', title: 'Conduit Systems', year: 2022 },
          { code: 'BS EN 61439', title: 'LV Switchgear', year: 2021 },
          { code: 'BS EN 61537', title: 'Cable Trays', year: 2022 },
          { code: 'BS EN 62040', title: 'UPS', year: 2021 },
          { code: 'BS EN 62305', title: 'Lightning Protection', year: 2022 },
        ]
      },
      {
        body: 'TIA/EIA', name: 'Telecommunications Industry Association', country: 'USA',
        standards: [
          { code: 'TIA-568.0', title: 'Generic Cabling Standard', year: 2021 },
          { code: 'TIA-568.1', title: 'Commercial Building Cabling', year: 2021 },
          { code: 'TIA-568.2', title: 'Balanced Twisted Pair Cabling', year: 2021 },
          { code: 'TIA-568.3', title: 'Fiber Optic Cabling', year: 2021 },
          { code: 'TIA-568.4', title: 'Coaxial Cabling', year: 2021 },
          { code: 'TIA-569', title: 'Pathways & Spaces', year: 2020 },
          { code: 'TIA-570', title: 'Residential Cabling', year: 2021 },
          { code: 'TIA-606', title: 'Administration Standard', year: 2020 },
          { code: 'TIA-607', title: 'Grounding & Bonding', year: 2020 },
          { code: 'TIA-862', title: 'Structured Cabling for Intelligent Buildings', year: 2021 },
          { code: 'TIA-942', title: 'Data Center Infrastructure', year: 2022 },
          { code: 'TIA-1179', title: 'Healthcare Cabling', year: 2021 },
          { code: 'TIA-4940', title: 'Smart Device Cabling', year: 2023 },
        ]
      },
    ];

    for (const group of codeGroups) {
      for (const std of group.standards) {
        id++;
        codes.push({
          id: `CODE-${String(id).padStart(4, '0')}`,
          code: std.code,
          title: std.title,
          year: std.year,
          body: group.body,
          bodyName: group.name,
          country: group.country,
          discipline: this._getDiscipline(std.title, std.code),
          summary: `Requirements for ${std.title.toLowerCase()} in ${group.country}`,
          activeVersion: std.year,
          lastRevision: std.year,
          category: this._getCategory(std.title, std.code),
        });
      }
    }

    console.log(`Codes V2 Generator: ${codes.length} codes created`);
    return codes;
  }

  _getDiscipline(title, code) {
    if (title.match(/concrete|formwork|curing|grout/i)) return 'Structural - Concrete';
    if (title.match(/steel|structural steel/i)) return 'Structural - Steel';
    if (title.match(/masonry|brick|block|mortar/i)) return 'Structural - Masonry';
    if (title.match(/seismic|wind|lateral/i)) return 'Structural - Seismic';
    if (title.match(/foundation/)) return 'Structural - Geotechnical';
    if (title.match(/plumbing|water|drain|pipe|sanitary|sewer/i)) return 'Mechanical - Plumbing';
    if (title.match(/hvac|ventilation|air|duct|heating|cooling|thermal/i)) return 'Mechanical - HVAC';
    if (title.match(/electrical|power|cable|switch|lighting|conduit/i)) return 'Electrical - Power';
    if (title.match(/fire alarm|detection|smoke|detector|alarm|signaling/i)) return 'Electrical - Fire Alarm';
    if (title.match(/telecom|network|cabling|data|fiber/i)) return 'Electrical - Low Current';
    if (title.match(/sprinkler|fire pump|hydrant|extinguisher|standpipe/i)) return 'Fire Protection';
    if (title.match(/fire|life safety|egress/i)) return 'Fire & Life Safety';
    if (title.match(/curtain wall|window|door|glazing|facade/i)) return 'Architectural - Facade';
    if (title.match(/roof|waterproof|membrane|insulation/i)) return 'Architectural - Envelope';
    if (title.match(/floor|ceiling|finish|tile|plaster|paint|gypsum/i)) return 'Architectural - Finishes';
    if (title.match(/energy|conservation|efficiency/i)) return 'Energy';
    if (title.match(/accessibility|barrier/i)) return 'Accessibility';
    if (title.match(/elevator|lift|escalator|conveyor/i)) return 'Equipment - Vertical Transport';
    if (title.match(/quality|management|environment|health|safety/i)) return 'Management';
    if (title.match(/bim|digital|information/i)) return 'BIM - Digital';
    if (title.match(/cement|aggregate|admixture/i)) return 'Materials - Concrete';
    if (title.match(/timber|wood|glulam/i)) return 'Structural - Timber';
    if (title.match(/aluminum/i)) return 'Structural - Aluminum';
    if (title.match(/geotextile|geomembrane|geogrid/i)) return 'Civil - Geotechnical';
    if (title.match(/road|pavement|asphalt/i)) return 'Civil - Transportation';
    if (title.match(/solar|photovoltaic/i)) return 'Renewable Energy';
    return 'General';
  }

  _getCategory(title, code) {
    if (code.startsWith('SBC')) return 'National Building Code';
    if (code.startsWith('IBC') || code.startsWith('IRC') || code.startsWith('IECC')) return 'International Building Code';
    if (code.startsWith('ACI')) return 'Concrete Standard';
    if (code.startsWith('AISC')) return 'Steel Standard';
    if (code.startsWith('ASTM')) return 'Materials Standard';
    if (code.startsWith('NFPA')) return 'Fire Safety Standard';
    if (code.startsWith('ASHRAE')) return 'HVAC/Energy Standard';
    if (code.startsWith('IEC')) return 'Electrical Standard';
    if (code.startsWith('ISO')) return 'International Standard';
    if (code.startsWith('BS EN')) return 'European/UK Standard';
    if (code.startsWith('BS ')) return 'UK Standard';
    if (code.startsWith('EN ')) return 'European Standard';
    if (code.startsWith('SASO')) return 'Saudi Standard';
    if (code.startsWith('DIN')) return 'German Standard';
    if (code.startsWith('UL')) return 'Safety Standard';
    if (code.startsWith('TIA') || code.startsWith('TIA/EIA')) return 'Telecom Standard';
    return 'Code';
  }
}
module.exports = { CodesV2Generator };
